# Generated by Django 3.2.9 on 2021-11-17 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0005_auto_20211117_0333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('product', models.ManyToManyField(related_name='shops', to='myshop.Product', verbose_name='Product')),
            ],
        ),
    ]
