# Generated by Django 3.2.9 on 2021-11-17 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0007_alter_shop_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='product',
            new_name='products',
        ),
    ]
