# Generated by Django 3.2.9 on 2021-11-17 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0008_rename_product_shop_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='is_official_reseller',
            field=models.BooleanField(default=False, verbose_name='Is official reseller'),
        ),
    ]
